rapidpro/data_api

.gitignore, README.md, data_api/api/tests.py, data_api/settings_common.py, data_api/settings_dev.py
@ewheeler just poking around a bit in here and documenting/fixing things to start
=> add setup instructions and fix tests

data_api/api/management/commands/import_org.py, data_api/api/models.py, data_api/api/tasks.py, data_api/api/tests.py, data_api/settings_common.py, data_api/settings_dev.py, requirements.txt
this is basically the minimal set of changes necessary for me to get the `fetch_all` task to run against my environment.
it's pretty incomplete at the moment but it runs and most of the data I've put in rapidpro is successfully getting imported again. 
there's also some other miscellaneous changes around environment setup / logging / etc.
next steps are:
- figure out how we're going to get all the messages (they have removed the ability to query an unfiltered list so we'll have to figure out how best to filter through everything)
- figure out what happened to the `Result` model from v1. It is [notably absent from the v2 API list](https://rapidpro.io/api/v2/).
- audit all v2 APIs / models one by one and and get everything relevant added/updated in our models
- build/update our API
- maybe …
=> Upgrade rapidpro client and APIs to v2

data_api/api/models.py, data_api/api/tests/test_data_import_v2.py
A few smallish changes getting the import functionality to be basically feature complete (though there are some known quirks with it that I'm tracking / will fix)
- added first and last synced attributes
- got message import working
- fixed a few bugs related to different datatypes on prod vs test data
- simplified / removed broken import pagination workflows
My plan is to switch gears to the other side of the API, try and get everything in place, and then come back to smooth out a few rough edges around import
=> Api updates

README.md, data_api/api/management/commands/import_org.py, data_api/api/models.py, data_api/api/utils.py, data_api/settings_common.py, docs/production.md, fabfile.py, requirements.txt
A few little :mag: details related to deployment.
=> Deployment

data_api/api/management/commands/fetch_all.py, data_api/api/models.py, data_api/api/tests/test_api_results/channel_events.json, requirements.txt
these changes also depend on https://github.com/rapidpro/rapidpro-python/pull/52 to work properly.
=> a few fixes related to running on larger data sets

README.md, data_api/api/management/commands/fetch_all.py, data_api/api/models.py, data_api/api/serializers.py, data_api/api/tests/test_api_results/campaigns.json, data_api/api/utils.py, data_api/settings_common.py
just a few more small odds and ends
=> Import tweaks

data_api/api/management/commands/fetch_all.py, data_api/api/tasks.py, data_api/celery.py, data_api/settings_common.py, requirements.txt
@ewheeler not sure when you're back, but I'm back working on this (finally)
this just makes some small celery changes to get things working again in the latest versions of things.
=> fix periodic task updating data

data_api/api/tasks.py, data_api/celery.py, data_api/settings_common.py, docs/production.md, requirements.txt
also switches update to run every day
=> tweaks to add better logging infrastructure around data update

data_api/api/urls.py, data_api/api/utils.py, data_api/settings_common.py, data_api/ui/forms.py, data_api/ui/templates/ui/import_org.html, data_api/ui/urls.py, data_api/ui/views.py, data_api/urls.py
@ewheeler I went to go import some more orgs and then decided it would probably be more long-term sustainable if doing this didn't require logging into the server and running stuff on the command line.
probably easiest to review by commit as the first one is just whitespace.
=> add very basic UI to enable users to import orgs

data_api/api/models.py, data_api/api/tests/test_fetch_args.py
@ewheeler so I just assumed that because it looked like there was checkpointing infrastructure that I didn't touch that it actually checkpointed, but on further inspection that proved wrong.
This should add checkpointing for the object types that support it (including messages, thankfully)
=> Fetch checkpoints

docs/production.md
=> update virtualenv location

data_api/api/management/commands/fetch_all.py, data_api/api/models.py, data_api/api/tasks.py, data_api/api/tests/test_data_import_v2.py
some tweaks to improve logging and reduce memory usage. previously everything created was being kept in a giant list and then thrown away. hoping maybe this helps speed up some of the large org imports
=> Sync tweaks

requirements.txt
this makes it compatible with postgres 10
=> bump psycopg version

.gitignore, data_api/api/models.py
some comments and changes based on doing some profiling and looking at where import is slow
=> Performance improvements

data_api/api/exceptions.py, data_api/api/management/commands/delete_org.py, data_api/api/models.py, data_api/api/tasks.py, data_api/api/tests/test_data_import_v2.py
- better handling of concurrent imports
- retry on rapidpro timeouts
- misc tests/fixes to tests
=> better import stability

data_api/settings_common.py, requirements.txt
this will allow us to use mailgun
=> add anymail support

requirements.txt
this matches our version of django (which fixes a bug with `IsAuthenticated` always returning true.
=> downgrade drf to match our version of django

data_api/staging/ingestion.py
this gives us something like this in sentry:
Instead of something like this:
=> use sentry scope to capture temba object

.gitignore, data_api/.travis.yml, data_api/staging/models.py, data_api/staging/tests/test_data_import.py, data_api/staging/utils.py, requirements.txt, tox.ini
added travis CI
added support to python3.7
added tox
=> travis - py3 compatible

fabfile.py
not sure how this wasn't already here... :see_no_evil:
=> migrate on deploy

data_api/staging/ingestion.py, data_api/staging/management/commands/delete_organization.py, data_api/staging/models.py, data_api/staging/tasks.py
@domdinicola some issues I ran to running (and troubleshooting) ingestion on py3
=> Py3 tweaks
